### PR TITLE
Fix build with GHC 8.8

### LINKED ISSUE #8: Does not build with ghc 8.8
Discussed with my friend @guibou who is a bit more handy than me with haskell. He said he'll do a PR

```
117   │ Building library for daemons-0.2.1..
118   │ [1 of 5] Compiling Control.Pipe.Serialize ( src/Control/Pipe/Serialize.hs, dist/dist-sandbox-3b586ae8/build/Control/Pipe/Serialize.o )
119   │
120   │ src/Control/Pipe/Serialize.hs:33:16: error:
121   │     • Could not deduce (MonadFail m) arising from a use of ‘loop’
122   │       from the context: (Serialize a, Monad m)
123   │         bound by the type signature for:
124   │                    deserializer :: forall a (m :: * -> *).
125   │                                    (Serialize a, Monad m) =>
126   │                                    Pipe ByteString a m ()
127   │         at src/Control/Pipe/Serialize.hs:32:1-64
128   │       Possible fix:
129   │         add (MonadFail m) to the context of
130   │           the type signature for:
131   │             deserializer :: forall a (m :: * -> *).
132   │                             (Serialize a, Monad m) =>
133   │                             Pipe ByteString a m ()
134   │     • In the expression: loop Nothing Nothing
135   │       In an equation for ‘deserializer’:
136   │           deserializer
137   │             = loop Nothing Nothing
138   │             where
139   │                 loop mk mbin
140   │                   = do bin <- maybe await return mbin
141   │                        ....
142   │    |
143   │ 33 | deserializer = loop Nothing Nothing
144   │    |                ^^^^^^^^^^^^^^^^^^^^
```

### PR DESCRIPTION
**Pull request by guibou**
This PR closes #8, and means that `daemons` now support GHC 8.8.

In order to do that, I had to:

- Add a `MonadFail` instance (needed for `Pipe`) on one function and add the associated import to keep compatibility with GHC 8.6
- Add support for newest `network` library. The API changed a bit and some function were deprecated.

The compatibility with older GHC version is done. I tested the build using the following nix expression:

```nix
with import <nixpkgs> {};
let
  makeDaemons = haskellPackages: networkName: haskellPackages.callCabal2nix "daemons"
    (builtins.filterSource (type: name: name != "default.nix") ./.)
    {
      network = builtins.getAttr networkName haskellPackages;
    };

  haskellCompilers = with haskell.packages; [ ghc882 ghc865 ghc844 ];
  # "network" is:
  # - 2.8.0.1 for ghc 8.6 and ghc 8.4
  # - 3.1.1.1 for ghc 8.8
  networkPackages = ["network" "network_3_0_1_1" "network_3_1_1_1"];

in lib.lists.crossLists (hs: network: makeDaemons hs network) [ haskellCompilers networkPackages ]
```

Meaning that I tested with ghc 8.4, 8.6 and 8.8. With `network` 3.0, 3.1 and 2.8 (except for ghc 8.8).

If accepted, could you do an hackage release? I suggest upgrading the major version number, considering that the API changed to add the `MonadFail` constraint.

### CODE REVIEW

**Comment by scvalex** [comment]
Done: https://hackage.haskell.org/package/daemons-0.3.0

Thanks for the fixes!
