### ISSUE TITLE
Does not build with ghc 8.8

### ISSUE THREAD

**Issue by gbataille** [scvalex/daemons#8]
Discussed with my friend @guibou who is a bit more handy than me with haskell. He said he'll do a PR

```
117   │ Building library for daemons-0.2.1..
118   │ [1 of 5] Compiling Control.Pipe.Serialize ( src/Control/Pipe/Serialize.hs, dist/dist-sandbox-3b586ae8/build/Control/Pipe/Serialize.o )
119   │
120   │ src/Control/Pipe/Serialize.hs:33:16: error:
121   │     • Could not deduce (MonadFail m) arising from a use of ‘loop’
122   │       from the context: (Serialize a, Monad m)
123   │         bound by the type signature for:
124   │                    deserializer :: forall a (m :: * -> *).
125   │                                    (Serialize a, Monad m) =>
126   │                                    Pipe ByteString a m ()
127   │         at src/Control/Pipe/Serialize.hs:32:1-64
128   │       Possible fix:
129   │         add (MonadFail m) to the context of
130   │           the type signature for:
131   │             deserializer :: forall a (m :: * -> *).
132   │                             (Serialize a, Monad m) =>
133   │                             Pipe ByteString a m ()
134   │     • In the expression: loop Nothing Nothing
135   │       In an equation for ‘deserializer’:
136   │           deserializer
137   │             = loop Nothing Nothing
138   │             where
139   │                 loop mk mbin
140   │                   = do bin <- maybe await return mbin
141   │                        ....
142   │    |
143   │ 33 | deserializer = loop Nothing Nothing
144   │    |                ^^^^^^^^^^^^^^^^^^^^
```
